aggregator:
  mongodb:
    host: mongo.esportstracker.net
    port: 27017
    ssl: True
postgres:
  db_name: esports_stats
  host: localhost
  port: 5432
twitch:
  api:
    game_ids: https://api.twitch.tv/kraken/search/games
    live_streams: https://api.twitch.tv/kraken/streams/?language=en&stream_type=live&limit=100&game={}
    top_games: https://api.twitch.tv/kraken/games/top/?limit=100
    user_ids: https://api.twitch.tv/kraken/users?login={}
    version: application/vnd.twitchtv.v5+json
  db:
    db_name: esports_stats
    host: 'localhost'
    port: 27017
    top_games: twitch_top_games
    top_streams: twitch_streams
  update_interval: 300
youtube:
  api:
    base_url: https://www.googleapis.com/youtube/v3
    num_results_per_request: 50
    top_3_videos_channel: https://www.googleapis.com/youtube/v3/search?part=snippet&channelId={CHANNEL_ID}&maxResults=10&order=date&type=video&key={YOUR_API_KEY}
  db:
    db_name: esports_stats
    host: 'localhost'
    port: 27017
    top_streams: youtube_streams
  esports_channels:
    League of Legends:
    - id: UCvqRdlKsE5Q8mf8YXbdIJLw
      name: LolChampSeries
  update_interval: 300
esportsgames:
  - 'Call of Duty: Infinite Warfare'
  - 'Counter-Strike: Global Offensive'
  - Dota 2
  - Hearthstone
  - Heroes of the Storm
  - League of Legends
  - Overwatch
  - PLAYERUNKNOWN'S BATTLEGROUNDS
  - Rocket League
  - Smite
  - StarCraft II
  - Street Fighter V
  - Super Smash Bros. Melee
