twitch:
  MLG:
  - id: '22212874'
    name: mlg
  - id: '48866350'
    name: mlgbravo
  Dreamhack:
  - id: '22859264'
    name: dreamhackcs
  - id: '64291396'
    name: dreamhackhs
  - id: '134543960'
    name: dreamhackoverwatch
  - id: '157859480'
    name: dreamhackrocketleague
  - id: '22859340'
    name: dreamhacksc2
  - id: '101390582'
    name: dreamhacksmash
  ESEA:
  - id: '8911047'
    name: esea
  - id: '28206345'
    name: esea2
  - id: '28547446'
    name: esea3
  ESL:
  - id: '31239503'
    name: esl_csgo
  - id: '35936871'
    name: esl_csgob
  - id: '132561587'
    name: proleaguecsgo
  - id: '36481935'
    name: esl_dota2
  - id: '82312665'
    name: esl_joindotared
  - id: '23660075'
    name: esl_overwatch
  - id: '30220059'
    name: esl_sc2
  FACEIT:
  - id: '27942990'
    name: faceittv
  - id: '55512799'
    name: faceittv2
  - id: '99132812'
    name: faceitproleague
  - id: '55675686'
    name: faceitcommunity
  - id: '59448778'
    name: gamesacademy
  - id: '44079069'
    name: beatesports
  - id: '447814'
    name: xgames
  Other:
  - id: '93141680'
    name: nvidiageforcepl
  ELEAGUE:
  - id: '109724636'
    name: eleaguetv
  PGL:
  - id: '21681549'
    name: pgl
  - id: '107953058'
    name: pgl_csgo
  - id: '106460795'
    name: dotamajor
  StarLadder:
  - id: '85875535'
    name: starladder_cs_en
  - id: '28633374'
    name: starladder5
  - id: '28633636'
    name: starladder10
  - id: '29578325'
    name: beyondthesummit
  - id: '29769280'
    name: beyondthesummit2
  - id: '54933969'
    name: dotastarladder_en
  - id: '54934114'
    name: dotastarladder_en2
  - id: '28633177'
    name: starladder1
  - id: '28633201'
    name: starladder2
  - id: '28633266'
    name: starladder3
  - id: '28633298'
    name: starladder4
  - id: '28633500'
    name: starladder7
  - id: '28633563'
    name: starladder8
  DreamLeague:
  - id: '50160915'
    name: dreamleague
  The International:
  - id: '35630634'
    name: dota2ti
  - id: '65503456'
    name: dota2ti_2
  - id: '65503845'
    name: dota2ti_3
  - id: '65503889'
    name: dota2ti_4
  - id: '96399910'
    name: dota2ti_newcomer
  - id: '96408506'
    name: dota2ti_workshop
  - id: '96400126'
    name: dota2ti_crowd

  Blizzard:
  - id: '42776357'
    name: playhearthstone
  - id: '48937001'
    name: blizzheroes
  - id: '125149756'
    name: cn_goldseries
  - id: '139607661'
    name: gcwc
  - id: '8822'
    name: blizzard
  - id: '42508152'
    name: starcraft
  TakeTV:
  - id: '52288508'
    name: taketv_hs
  - id: '107551531'
    name: taketv_overwatch
  - id: '30186974'
    name: taketv
  Riot:
  - id: '124420521'
    name: nalcs1
  - id: '124421740'
    name: nalcs2
  - id: '124422593'
    name: eulcs1
  - id: '124424929'
    name: eulcs2
  - id: '124425627'
    name: lpl1
  - id: '124427423'
    name: lpl2
  - id: '124425501'
    name: lck1
  - id: '124425092'
    name: lck2
  - id: '36029255'
    name: riotgames
  - id: '36794584'
    name: riotgames2
  - id: '45982670'
    name: riotgameseu
  - id: '49649564'
    name: naclesports
  OGN:
  - id: '32179353'
    name: ognglobal
  Bluehole:
  - id: '127506955'
    name: playbattlegrounds
  Gfinity:
  - id: '92094149'
    name: rocketleaguecentral
  Psyonix:
  - id: '57781936'
    name: rocketleague
  Throwdown:
  - id: '118999468'
    name: throwdowntv
  Hi-Rez Studios:
  - id: '31542318'
    name: smitegame
  - id: '31500812'
    name: hireztv
  GSL:
  - id: '52229024'
    name: gsl
  2GGaming:
  - id: '10384419'
    name: 2ggaming
  EVO:
  - id: '30917811'
    name: srkevo1
  - id: '30918314'
    name: srkevo2
  - id: '31245897'
    name: srkevo3
  - id: '45870383'
    name: srkevo4
  - id: '36616300'
    name: capcomfighters
