aggregator:
  mongodb:
    host: mongo.esportstracker.net
    db_name: esports_stats
    port: 27017
    ssl: True
    #host: 'localhost'
    #ssl: False
postgres:
  db_name: esports_stats
  host: localhost
  port: 5432
twitch:
  api:
    host: https://api.twitch.tv/
  db:
    db_name: esports_stats
    host: 'localhost'
    port: 27017
  update_interval: 600
twitch_channel_scraper:
  api:
    host: https://api.twitch.tv/
  mongodb:
    #host: localhost
    #ssl: False
    host: mongo.esportstracker.net
    ssl: True
    db_name: esports_stats
    port: 27017
  update_interval: 600
youtube_channel_scraper:
  api:
    host: https://www.googleapis.com/youtube/v3
  mongodb:
    #host: localhost
    #ssl: False
    host: mongo.esportstracker.net
    ssl: True
    db_name: esports_stats
    port: 27017
  update_interval: 600
youtube:
  api:
    base_url: https://www.googleapis.com/youtube/v3
  db:
    db_name: esports_stats
    host: 'localhost'
    port: 27017
  update_interval: 600
esportsgames:
  - {id: 491437, name: 'Call of Duty: Infinite Warfare'}
  - {id: 32399, name: 'Counter-Strike: Global Offensive'}
  - {id: 29595, name: Dota 2}
  - {id: 138585, name: Hearthstone}
  - {id: 32959, name: Heroes of the Storm}
  - {id: 21779, name: League of Legends}
  - {id: 488552, name: Overwatch}
  - {id: 493057, name: PLAYERUNKNOWN'S BATTLEGROUNDS}
  - {id: 30921, name: Rocket League}
  - {id: 32507, name: Smite}
  - {id: 490422, name: StarCraft II}
  - {id: 488615, name: Street Fighter V}
  - {id: 16282, name: Super Smash Bros. Melee}
  - {id: 417892, name: 'H1Z1: King of the Kill'}
  - {id: 496712, name: 'Call of Duty: WWII'}
