twitch:
  2GGaming:
  - {id: 10384419, name: 2GGaming}
  Blizzard:
  - {id: 42776357, name: PlayHearthstone}
  - {id: 48937001, name: Heroes of the Storm}
  - {id: 125149756, name: CN_Goldseries}
  - {id: 139607661, name: GCWC}
  - {id: 8822, name: Blizzard}
  - {id: 42508152, name: StarCraft}
  - {id: 22212874, name: MLG}
  - {id: 48866350, name: mlgbravo}
  Bluehole:
  - {id: 127506955, name: playBATTLEGROUNDS}
  CyberPower:
  - {id: 49946840, name: CyberPowerGaming}
  DreamLeague:
  - {id: 50160915, name: DreamLeague}
  Dreamhack:
  - {id: 22859264, name: DreamHackCS}
  - {id: 64291396, name: DreamHackHS}
  - {id: 134543960, name: dreamhackoverwatch}
  - {id: 157859480, name: DreamHackRocketLeague}
  - {id: 22859340, name: DreamhackSC2}
  - {id: 101390582, name: DreamHackSmash}
  ELEAGUE:
  - {id: 109724636, name: ELEAGUE TV}
  ESEA:
  - {id: 8911047, name: ESEA}
  - {id: 28206345, name: ESEA2}
  - {id: 28547446, name: ESEA3}
  ESL:
  - {id: 31239503, name: ESL_CSGO}
  - {id: 35936871, name: ESL_CSGOb}
  - {id: 132561587, name: ProLeagueCSGO}
  - {id: 36481935, name: ESL_DOTA2}
  - {id: 82312665, name: joinDOTARed}
  - {id: 23660075, name: ESL_Overwatch}
  - {id: 30220059, name: ESL_SC2}
  EVO:
  - {id: 30917811, name: SRKEvo1}
  - {id: 30918314, name: SRKEvo2}
  - {id: 31245897, name: SRKEvo3}
  - {id: 45870383, name: SRKEvo4}
  - {id: 36616300, name: CapcomFighters}
  Epic Esports Events:
  - {id: 118170488, name: epicenter_en1}
  - {id: 118170598, name: epicenter_en2}
  - {id: 126779203, name: d2cl_en}
  FACEIT:
  - {id: 27942990, name: FACEIT TV}
  - {id: 55512799, name: FACEITTV2}
  - {id: 99132812, name: FACEITProLeague}
  - {id: 55675686, name: FACEITCommunity}
  - {id: 59448778, name: GamesAcademy}
  - {id: 44079069, name: BEATesports}
  - {id: 447814, name: xgames}
  GSL:
  - {id: 52229024, name: GSL}
  Gfinity:
  - {id: 92094149, name: RocketLeagueCentral}
  Hi-Rez Studios:
  - {id: 31542318, name: smitegame}
  - {id: 31500812, name: HiRezTV}
  OGN:
  - {id: 32179353, name: OGNGlobal}
  Other:
  - {id: 93141680, name: NVIDIAGeForcePL}
  PGL:
  - {id: 21681549, name: PGL}
  - {id: 107953058, name: pgl_csgo}
  - {id: 106460795, name: DotaMajor}
  Psyonix:
  - {id: 57781936, name: RocketLeague}
  Riot Games:
  - {id: 124420521, name: NALCS1}
  - {id: 124421740, name: NALCS2}
  - {id: 124422593, name: EULCS1}
  - {id: 124424929, name: EULCS2}
  - {id: 124425627, name: LPL1}
  - {id: 124427423, name: LPL2}
  - {id: 124425501, name: LCK1}
  - {id: 124425092, name: LCK2}
  - {id: 36029255, name: Riot Games}
  - {id: 36794584, name: RiotGames2}
  - {id: 45982670, name: RiotGamesEU}
  - {id: 49649564, name: NACLeSports}
  StarLadder:
  - {id: 85875535, name: Starladder_CS_en}
  - {id: 28633374, name: Starladder5}
  - {id: 28633636, name: Starladder10}
  - {id: 29578325, name: BeyondTheSummit}
  - {id: 29769280, name: BeyondTheSummit2}
  - {id: 54933969, name: dotastarladder_en}
  - {id: 54934114, name: dotastarladder_en2}
  - {id: 28633177, name: Starladder1}
  - {id: 28633201, name: Starladder2}
  - {id: 28633266, name: Starladder3}
  - {id: 28633298, name: Starladder4}
  - {id: 28633500, name: starladder7}
  - {id: 28633563, name: starladder8}
  TakeTV:
  - {id: 52288508, name: TaKeTV_HS}
  - {id: 107551531, name: TaKeTV_Overwatch}
  - {id: 30186974, name: TaKeTV}
  Throwdown:
  - {id: 118999468, name: ThrowdownTV}
  VGBootCamp:
  - {id: 9846758, name: VGBootCamp}
  Valve Corporation:
  - {id: 35630634, name: dota2ti}
  - {id: 65503456, name: dota2ti_2}
  - {id: 65503845, name: dota2ti_3}
  - {id: 65503889, name: dota2ti_4}
  - {id: 96399910, name: dota2ti_newcomer}
  - {id: 96408506, name: dota2ti_workshop}
  - {id: 96400126, name: dota2ti_crowd}
youtube:
  Blizzard:
  - {id: UCzSItlUKaVNWbd7ybbfnFhg, name: MajorLeagueGaming}
  - {id: UCbLIqv9Puhyp9_ZjVtfOy7w, name: OfficialMLGCoD}
  - {id: UC3GriadTkHBnfgd2UFETGOA, name: blizzard}
  - {id: UClOf1XXinvZsy4wKPAkro2A, name: PlayOverwatch}
  ESL:
  - {id: UCPq2ETz4aAGo2Z-8JisDPIA, name: ESL Counter-Strike}
  FACEIT:
  - {id: UCajcK9vEBDLmcLSSYf4WXVA, name: FACEITcom}
  PGL:
  - {id: UC5jpxDZx4yoBo324pMQ91Ww, name: PGLeSport}
  Riot Games:
  - {id: UCvqRdlKsE5Q8mf8YXbdIJLw, name: LolChampSeries}
  Valve Corporation:
  - {id: UCTQKT5QqO3h7y32G8VzuySQ, name: dota2}
