esports:
  Dota 2:
    ytid: UCoT0xCPOr0vSNW09FZPbVQQ
    tid: 29595
  'Counter-Strike: Global Offensive':
    ytid: UCiVA5GplC-m8qzChGuzahRg
    tid: 32399
  Hearthstone:
    ytid: UCNbEdsRTnu2bOSoTCWGznqA
    tid: 138585
  Overwatch:
    ytid: UCONmUmaDEnG94vzGwtMxdKQ
    tid: 488552
  PLAYERUNKNOWN'S BATTLEGROUNDS:
    ytid: UCnXDQbqIdp-HQuDyM4p12ng
    tid: 493057
  League of Legends:
    ytid: UCsZ9w8wgYJc4eea6oI-3HLQ
    tid: 21779
  Heroes of the Storm:
    ytid: UCxzJ9le0-E779Lc0ItXLXiw
    tid: 32959
  Rocket League:
    ytid: UCUqaFJos6uKL3G25YrVKWWQ
    tid: 30921
  StarCraft II:
    ytid: UCg4Bmooi0HQh7KTwswup95g
    tid: 490422
  Smite:
    ytid: UCfcK1A4HBfoVC5PgTG-e7Ug
    tid: 32507
  Street Fighter V:
    ytid: UCDrC4V2A8BelGGuTEQXffhQ
    tid: 488615
  'Call of Duty: Infinite Warfare':
    ytid: UCUL-o8O7cUBfdJKczVNbkBQ
    tid: 491437
  Super Smash Bros. Melee:
    ytid: UCM1fPpzWUd3K8HmPwVqhMRQ
    tid: 16282
